"""Loopback HTTP surface between the Tauri host and this sidecar.

Security model: bind 127.0.0.1 only (uvicorn invocation, M4), ephemeral port, bearer token
generated by the Rust host and passed via env. Every route requires the token EXCEPT /healthz.
Progress streams over SSE so the Run Line UI animates live.
"""

from __future__ import annotations

import json
import logging
import queue
import threading
import asyncio
from contextlib import asynccontextmanager
from pathlib import Path

from fastapi import Depends, FastAPI, Header, HTTPException, Request
from fastapi.middleware.cors import CORSMiddleware

from atme import __version__

log = logging.getLogger(__name__)


class JobHub:
    """In-process pub/sub for job progress events."""

    def __init__(self) -> None:
        self._subs: dict[int, list["queue.Queue"]] = {}
        self._lock = threading.Lock()

    def subscribe(self, job_id: int) -> queue.Queue:
        q: queue.Queue = queue.Queue()
        with self._lock:
            self._subs.setdefault(job_id, []).append(q)
        return q

    def publish(self, job_id: int, event: dict) -> None:
        with self._lock:
            subs = list(self._subs.get(job_id, []))
        for q in subs:
            q.put(event)

    def unsubscribe(self, job_id: int, q: queue.Queue) -> None:
        with self._lock:
            if job_id in self._subs and q in self._subs[job_id]:
                self._subs[job_id].remove(q)


def _auth_dependency(token: str):
    def check(authorization: str = Header(default="")) -> None:
        expected = "Bearer %s" % token
        if authorization != expected:
            raise HTTPException(status_code=401, detail="bad token")
    return check


def create_app(token: str = "dev-token", orchestrator=None) -> FastAPI:
    _token = token
    from atme.store.db import STAGE_ORDER, JobStore

    hub = JobHub()
    orch = orchestrator
    db_path = getattr(orchestrator, "store", None) and orchestrator.store.db_path
    own_store = db_path is None
    store = orchestrator.store if not own_store else JobStore("data/jobs/jobs.db")
    auth = _auth_dependency(token)
    running: set[int] = set()
    lock = threading.Lock()
    worker_gate = threading.Lock()
    model_prep = {"status": "not_ready", "error": None}
    model_lock = threading.Lock()

    @asynccontextmanager
    async def lifespan(_app: FastAPI):
        recover_interrupted_jobs()
        yield

    app = FastAPI(title="ATME sidecar", version=__version__,
                  docs_url=None, redoc_url=None, lifespan=lifespan)
    from atme.mcp_activity import LiveMcpSessions
    app.state.live_mcp = LiveMcpSessions()
    from atme.server.projects import register_projects
    app.state.projects = register_projects(app, store, auth)
    from atme.server.board_proposals import register_board_proposals
    register_board_proposals(app, orchestrator, store, auth, lock, running)
    app.add_middleware(
        CORSMiddleware,
        allow_origins=["http://tauri.localhost", "https://tauri.localhost",
                       "http://localhost:5173", "http://127.0.0.1:5173"],
        allow_methods=["*"], allow_headers=["*"])

    @app.get("/healthz")
    def healthz() -> dict:
        return {"status": "ok", "sidecar": True, "version": __version__}

    @app.post("/shutdown", dependencies=[Depends(auth)])
    def shutdown(request: Request) -> dict:
        # Graceful path: flip uvicorn's should_exit; the Rust supervisor PID-kills as backstop.
        server_obj = getattr(request.app.state, "uvicorn_server", None)
        if server_obj is not None:
            server_obj.should_exit = True
        return {"accepted": True}

    @app.post("/mcp/live", dependencies=[Depends(auth)])
    async def mcp_live(request: Request) -> dict:
        raw = await request.body()
        if len(raw) > 16 * 1024:
            raise HTTPException(413, "MCP event is too large")
        try:
            payload = json.loads(raw)
            if not isinstance(payload, dict):
                raise ValueError()
            return app.state.live_mcp.update(payload)
        except (ValueError, UnicodeError):
            raise HTTPException(400, "Invalid MCP event")

    @app.get("/settings/providers", dependencies=[Depends(auth)])
    def provider_settings() -> dict:
        return {"configured": False, "roles": {}, "mode": "external", "api_keys_required": False}

    @app.put("/settings/providers", dependencies=[Depends(auth)])
    def save_provider_settings(body: dict) -> dict:
        raise HTTPException(410, "Provider setup retired. Import external script and layout; no API keys required.")

    @app.get("/models/alignment", dependencies=[Depends(auth)])
    def alignment_model_status() -> dict:
        with model_lock:
            return dict(model_prep)

    @app.post("/models/alignment", dependencies=[Depends(auth)])
    def prepare_alignment_model() -> dict:
        with model_lock:
            if model_prep["status"] in ("preparing", "ready"):
                return {**model_prep, "accepted": False}
            model_prep.update(status="preparing", error=None)

        def prepare() -> None:
            try:
                from atme.audio.align import _get_model

                _get_model()
                with model_lock:
                    model_prep.update(status="ready", error=None)
            except Exception as exc:  # noqa: BLE001 - surfaced to Settings and job logs
                log.exception("alignment model preparation failed")
                with model_lock:
                    model_prep.update(status="failed", error=str(exc)[:300])

        threading.Thread(target=prepare, daemon=True).start()
        return {"accepted": True, "status": "preparing", "error": None}

    @app.get("/jobs", dependencies=[Depends(auth)])
    def list_jobs() -> dict:
        with store._lock:
            rows = store.conn.execute(
                "SELECT j.id, j.topic, j.title, j.status, j.created_at, "
                "(SELECT a.path FROM artifacts a WHERE a.job_id=j.id AND a.kind='video' "
                " ORDER BY a.id DESC LIMIT 1) AS video_path, "
                "(SELECT a.bytes FROM artifacts a WHERE a.job_id=j.id AND a.kind='video' "
                " ORDER BY a.id DESC LIMIT 1) AS video_bytes, "
                "COALESCE((SELECT SUM(u.cost_usd) FROM llm_usage u WHERE u.job_id=j.id),0) "
                "AS cost_usd "
                "FROM jobs j ORDER BY j.id DESC"
            ).fetchall()
        jobs = []
        for row in rows:
            item = dict(row)
            item["duration_ms"] = None
            if item.get("video_path"):
                manifest = Path(item["video_path"]).parent.parent / "manifest.json"
                try:
                    item["duration_ms"] = json.loads(
                        manifest.read_text(encoding="utf-8")).get("duration_ms")
                except (OSError, json.JSONDecodeError):
                    pass
            jobs.append(item)
        return {"jobs": jobs}

    @app.post("/jobs/external", dependencies=[Depends(auth)])
    async def import_external(request: Request) -> dict:
        from atme.external_inputs import validate_external_inputs
        from jsonschema import ValidationError
        if orch is None:
            raise HTTPException(503, "orchestrator not wired")
        raw = bytearray()
        async for chunk in request.stream():
            raw.extend(chunk)
            if len(raw) > 12 * 1024 * 1024:
                raise HTTPException(413, "external input exceeds 12 MiB")
        try:
            body = json.loads(raw)
            if not isinstance(body, dict) or set(body) != {"script", "layout"}:
                raise ValueError("provide script and layout only")
            script, layout = validate_external_inputs(body["script"], body["layout"])
        except (ValueError, TypeError, KeyError, ValidationError):
            raise HTTPException(400, "invalid external script/layout; check schemas, scene IDs and board timing")
        job_id = store.create_job(topic=script["topic"], settings={
            "provider": "external", "voice": "upload", "review_gate": True,
            "width": 1280, "height": 720, "fps": 30})
        directory = orch._job_dir(job_id)
        directory.mkdir(parents=True, exist_ok=True)
        try:
            for name, value in (("script", script), ("layout", layout)):
                (directory / f"{name}.json").write_text(json.dumps(value, indent=2), encoding="utf-8")
            (directory / "external-inputs.original.json").write_bytes(raw)
            for stage in STAGE_ORDER:
                store.ensure_stage(job_id, stage)
            for stage in ("created", "scripted", "laid_out"):
                store.start_stage(job_id, stage)
                store.finish_stage(job_id, stage, ok=True)
            store.set_job_status(job_id, "paused")
        except Exception:
            store.set_job_status(job_id, "failed")
            raise HTTPException(500, "external import could not be saved; job remains recoverable")
        return {"job_id": job_id, "status": "paused", "requires_review": True, "provider": "external"}

    @app.post("/jobs", dependencies=[Depends(auth)])
    def submit_job(body: dict) -> dict:
        raise HTTPException(410, "Internal topic generation retired. Use /jobs/external to import a script and layout.")

    def spawn_worker(job_id: int) -> bool:
        with lock:
            if job_id in running:
                return False
            running.add(job_id)

        def worker() -> None:
            worker_gate.acquire()
            try:
                result = orch.run_job(
                    job_id,
                    progress_cb=lambda phase, jid: hub.publish(jid, {"phase": phase}))
                if result.get("waiting_voice"):
                    hub.publish(job_id, {"phase": "waiting_voice"})
                elif result.get("paused"):
                    hub.publish(job_id, {"phase": "paused_review"})
                else:
                    m = result["manifest"]
                    hub.publish(job_id, {"phase": "done",
                                         "video": m["artifacts"]["video"]["path"]})
            except Exception as exc:  # noqa: BLE001 - report through stream
                from atme.audio.voice_upload import VoiceScriptMismatch
                from atme.orchestrator import JobCanceled, JobPaused

                if isinstance(exc, JobPaused):
                    hub.publish(job_id, {"phase": "paused"})
                    return
                if isinstance(exc, JobCanceled):
                    hub.publish(job_id, {"phase": "canceled"})
                    return
                if isinstance(exc, VoiceScriptMismatch):
                    store.set_job_status(job_id, "voice_rejected")
                    store.log(job_id, str(exc), level="error")
                    hub.publish(job_id, {"phase": "voice_rejected",
                                         "error": str(exc)[:300]})
                    return
                log.exception("job %s failed", job_id)
                store.set_job_status(job_id, "failed")
                store.log(job_id, str(exc)[:500], level="error")
                hub.publish(job_id, {"phase": "failed", "error": str(exc)[:300]})
            finally:
                worker_gate.release()
                with lock:
                    running.discard(job_id)

        threading.Thread(target=worker, daemon=True).start()
        return True

    @app.post("/jobs/{job_id}/run", dependencies=[Depends(auth)])
    def run_job(job_id: int) -> dict:
        if orch is None:
            raise HTTPException(503, "orchestrator not wired into this sidecar instance")
        accepted = spawn_worker(job_id)
        return {"accepted": accepted, **({} if accepted else {"reason": "already running"})}

    @app.post("/jobs/{job_id}/control", dependencies=[Depends(auth)])
    def control_job(job_id: int, body: dict) -> dict:
        job = store.get_job(job_id)
        if not job:
            raise HTTPException(404, "no such job")
        action = str(body.get("action") or "").lower()
        if action == "pause":
            if job["status"] not in ("running", "pause_requested"):
                raise HTTPException(409, "only a running job can be paused")
            store.set_job_status(job_id, "pause_requested")
            hub.publish(job_id, {"phase": "pause_requested"})
            return {"accepted": True, "status": "pause_requested"}
        if action == "resume":
            if job["status"] not in ("paused", "failed"):
                raise HTTPException(409, "only a paused or failed job can be resumed")
            store.set_job_status(job_id, "running")
            return {"accepted": spawn_worker(job_id), "status": "running"}
        if action == "cancel":
            if job["status"] in ("done", "canceled"):
                raise HTTPException(409, "job is already terminal")
            with lock:
                active = job_id in running
            status = "cancel_requested" if active else "canceled"
            store.set_job_status(job_id, status)
            hub.publish(job_id, {"phase": status})
            return {"accepted": True, "status": status}
        raise HTTPException(400, "action must be pause, resume, or cancel")

    @app.post("/jobs/{job_id}/review", dependencies=[Depends(auth)])
    def review(job_id: int, body: dict) -> dict:
        if not store.get_job(job_id):
            raise HTTPException(404, "no such job")
        approved = bool(body.get("approved"))
        if not approved:
            store.set_job_status(job_id, "canceled")
            return {"accepted": True, "status": "canceled"}
        # Optional scene edits: replace script.json scenes wholesale.
        scenes = body.get("scenes")
        jdir = orch._job_dir(job_id) if orch is not None else None
        if scenes is not None and jdir is not None:
            sp = jdir / "script.json"
            if sp.exists():
                doc = json.loads(sp.read_text(encoding="utf-8"))
                if store.get_job(job_id)["settings"].get("provider") == "external" and scenes != doc["scenes"]:
                    raise HTTPException(409, "external script changed; import a revised script and matching layout as a new project")
                doc["scenes"] = scenes
                from jsonschema import Draft202012Validator
                from atme.resources import resource_path

                schema = json.loads(resource_path(
                    "schemas", "script-scenes.schema.json").read_text(encoding="utf-8"))
                errors = [error.message for error in
                          Draft202012Validator(schema).iter_errors(doc)]
                scene_ids = [scene.get("scene_id") for scene in scenes
                             if isinstance(scene, dict)]
                if len(scene_ids) != len(set(scene_ids)):
                    errors.append("scene_id values must be unique")
                if errors:
                    raise HTTPException(400, "invalid edited script: " + "; ".join(errors[:5]))
                sp.write_text(json.dumps(doc, indent=2), encoding="utf-8")
        store.start_stage(job_id, "reviewed")
        if jdir is not None and (jdir / "script.json").exists():
            orch._attach_file(job_id, "reviewed", "approved_script", jdir / "script.json")
        store.finish_stage(job_id, "reviewed", ok=True)
        job = store.get_job(job_id)
        if job and job["settings"].get("voice") == "upload" and not (
                orch._job_dir(job_id) / "audio" / "upload.wav").exists():
            store.set_job_status(job_id, "waiting_voice")
            hub.publish(job_id, {"phase": "waiting_voice"})
            return {"accepted": True, "status": "waiting_voice", "resumed": False}
        store.set_job_status(job_id, "running")
        hub.publish(job_id, {"phase": "review_approved"})
        spawned = spawn_worker(job_id) if orch is not None else False
        return {"accepted": True, "status": "running", "resumed": spawned}

    @app.post("/jobs/{job_id}/voice", dependencies=[Depends(auth)])
    async def upload_voice(job_id: int, request: Request,
                           x_filename: str = Header(default="voice.wav")) -> dict:
        if orch is None:
            raise HTTPException(503, "orchestrator not wired")
        job = store.get_job(job_id)
        if not job:
            raise HTTPException(404, "no such job")
        if job["settings"].get("voice") != "upload":
            raise HTTPException(409, "job is not configured for uploaded voice")
        from atme.audio.voice_upload import (MAX_UPLOAD_BYTES, VoiceUploadError,
                                             replace_uploaded_file)

        length = request.headers.get("content-length")
        try:
            if length and int(length) > MAX_UPLOAD_BYTES:
                raise HTTPException(413, "voiceover exceeds the 1 GB limit")
        except ValueError as exc:
            raise HTTPException(400, "invalid content-length") from exc

        audio_dir = orch._job_dir(job_id) / "audio"
        audio_dir.mkdir(parents=True, exist_ok=True)
        staged = audio_dir / ".voice-upload.part"
        received = 0
        try:
            with staged.open("wb") as fh:
                async for chunk in request.stream():
                    received += len(chunk)
                    if received > MAX_UPLOAD_BYTES:
                        raise HTTPException(413, "voiceover exceeds the 1 GB limit")
                    fh.write(chunk)
            source, quality = replace_uploaded_file(
                orch._job_dir(job_id), x_filename, staged)
        except HTTPException:
            staged.unlink(missing_ok=True)
            raise
        except VoiceUploadError as exc:
            staged.unlink(missing_ok=True)
            raise HTTPException(400, str(exc)) from exc
        except OSError as exc:
            staged.unlink(missing_ok=True)
            raise HTTPException(500, "could not store the voiceover") from exc

        store.reset_from_stage(job_id, "voiced")
        store.set_job_status(job_id, "running")
        store.log(job_id, "uploaded original voiceover: %s" % source.name)
        spawned = spawn_worker(job_id)
        return {"accepted": spawned, "status": "running", "quality": quality}

    @app.get("/jobs/{job_id}/voice-report", dependencies=[Depends(auth)])
    def voice_report(job_id: int) -> dict:
        if orch is None:
            raise HTTPException(503, "orchestrator not wired")
        audio_dir = orch._job_dir(job_id) / "audio"
        report = audio_dir / "voice_report.json"
        quality = audio_dir / "upload_quality.json"
        if not report.exists() and not quality.exists():
            raise HTTPException(404, "voice report is not ready")
        return {
            "quality": json.loads(quality.read_text(encoding="utf-8")) if quality.exists() else None,
            "comparison": json.loads(report.read_text(encoding="utf-8")) if report.exists() else None,
        }

    @app.get("/jobs/{job_id}", dependencies=[Depends(auth)])
    def job_state(job_id: int) -> dict:
        job = store.get_job(job_id)
        if not job:
            raise HTTPException(404, "no such job")
        first, done = store.resume_point(job_id)
        with store._lock:
            rows = store.conn.execute(
                "SELECT s.name,s.status,s.attempt,s.error FROM stages s "
                "JOIN (SELECT name,MAX(attempt) attempt FROM stages WHERE job_id=? "
                "GROUP BY name) latest ON latest.name=s.name AND latest.attempt=s.attempt "
                "WHERE s.job_id=? ORDER BY s.rowid", (job_id, job_id)).fetchall()
        stages = sorted((dict(r) for r in rows),
                        key=lambda item: STAGE_ORDER.index(item["name"]))
        return {"job": job, "stages": stages,
                "resume_point": first, "done_stages": done}

    @app.get("/jobs/{job_id}/boards", dependencies=[Depends(auth)])
    def board_editor(job_id: int) -> dict:
        import hashlib
        if orch is None:
            raise HTTPException(503, "orchestrator not wired")
        if not store.get_job(job_id):
            raise HTTPException(404, "no such job")
        directory = orch._job_dir(job_id)
        if not (directory / "layout.json").exists() or not (directory / "audio_state.json").exists():
            raise HTTPException(409, "board authoring needs a saved layout and final polished audio")
        raw = (directory / "layout.json").read_bytes()
        doc = json.loads(raw)
        audio = json.loads((directory / "audio_state.json").read_text(encoding="utf-8"))
        return {"revision": hashlib.sha256(raw).hexdigest(), "duration_ms": audio["duration_ms"],
                "timeline": doc.get("board_timeline"),
                "elements": [{k: e[k] for k in ("id", "scene_id", "type", "appear_at_ms", "board_id", "narration_trigger") if k in e}
                             for e in doc["elements"]]}

    @app.put("/jobs/{job_id}/boards", dependencies=[Depends(auth)])
    async def save_boards(job_id: int, request: Request) -> dict:
        import hashlib
        from uuid import uuid4
        from atme.board_edit import apply_board_edit
        if orch is None:
            raise HTTPException(503, "orchestrator not wired")
        raw = bytearray()
        async for chunk in request.stream():
            raw.extend(chunk)
            if len(raw) > 1024 * 1024:
                raise HTTPException(413, "board edit exceeds 1 MiB")
        try:
            payload = json.loads(raw)
            if not isinstance(payload, dict) or set(payload) != {"revision", "timeline", "assignments"}:
                raise ValueError()
        except ValueError:
            raise HTTPException(400, "invalid board edit request")
        with lock:
            job = store.get_job(job_id)
            if not job:
                raise HTTPException(404, "no such job")
            if job_id in running or job["status"] not in ("paused", "done", "failed", "waiting_voice", "paused_review"):
                raise HTTPException(409, "stop the job before editing boards")
            if "laid_out" not in store.resume_point(job_id)[1]:
                raise HTTPException(409, "finish layout before editing boards")
            directory = orch._job_dir(job_id)
            layout = directory / "layout.json"
            audio = directory / "audio_state.json"
            if not layout.exists() or not audio.exists():
                raise HTTPException(409, "saved layout and final audio required")
            original = layout.read_bytes()
            if hashlib.sha256(original).hexdigest() != payload["revision"]:
                raise HTTPException(409, "layout changed; reload the board editor")
            try:
                doc = apply_board_edit(json.loads(original), payload["timeline"], payload["assignments"],
                                       json.loads(audio.read_text(encoding="utf-8"))["duration_ms"])
            except (ValueError, TypeError, KeyError):
                raise HTTPException(400, "invalid board timeline or element assignment; check intervals, IDs and final-audio bounds")
            revision = uuid4().hex
            (directory / ("layout.before-boards-" + revision + ".json")).write_bytes(original)
            pending = directory / ("layout.boards-" + revision + ".pending.json")
            pending.write_text(json.dumps(doc, indent=2), encoding="utf-8")
            store.reset_from_stage(job_id, "aligned")
            pending.replace(layout)
            store.set_job_status(job_id, "paused")
        return {"saved": True, "status": "paused", "requires_realign": True}

    @app.get("/jobs/{job_id}/evidence", dependencies=[Depends(auth)])
    def evidence_slots(job_id: int) -> dict:
        if orch is None:
            raise HTTPException(503, "orchestrator not wired")
        if not store.get_job(job_id):
            raise HTTPException(404, "no such job")
        layout = orch._job_dir(job_id) / "layout.json"
        if not layout.exists():
            return {"slots": [], "boards": [], "activations": [], "canvas": None}
        doc = json.loads(layout.read_text(encoding="utf-8"))
        return {"boards": doc.get("board_timeline", {}).get("boards", []),
                "activations": doc.get("board_timeline", {}).get("activations", []),
                "canvas": doc["canvas"],
                "slots": [{"id": e["id"], "scene_id": e["scene_id"],
                           "provenance": e["provenance"]} for e in doc["elements"]
                          if e.get("type") == "evidence_image"]}

    @app.post("/jobs/{job_id}/evidence/{element_id}", dependencies=[Depends(auth)])
    @app.put("/jobs/{job_id}/evidence/{element_id}", dependencies=[Depends(auth)])
    async def replace_evidence(job_id: int, element_id: str, request: Request) -> dict:
        if orch is None:
            raise HTTPException(503, "orchestrator not wired")
        # Bound the JSON body before parsing base64. No filenames or paths are accepted.
        body = bytearray()
        async for chunk in request.stream():
            body.extend(chunk)
            if len(body) > 12 * 1024 * 1024:
                raise HTTPException(413, "evidence request exceeds 12 MiB")
        try:
            payload = json.loads(body)
            creating = request.method == "POST"
            required = {"png_base64", "sha256", "provenance"} | ({"placement"} if creating else set())
            if not isinstance(payload, dict) or set(payload) != required:
                raise ValueError()
            placement = payload.pop("placement", None)
            if creating and (not isinstance(placement, dict) or set(placement) != {
                    "scene_id", "board_id", "appear_at_ms", "x", "y", "width", "height"}):
                raise ValueError()
        except (ValueError, UnicodeError):
            raise HTTPException(400, "provide PNG content, checksum and provenance only")
        from atme.store.contracts import LayoutDoc
        from uuid import uuid4

        with lock:
            job = store.get_job(job_id)
            if not job:
                raise HTTPException(404, "no such job")
            if job_id in running or job["status"] not in ("paused", "failed", "done", "waiting_voice", "paused_review"):
                raise HTTPException(409, "stop the job before replacing evidence")
            _, done = store.resume_point(job_id)
            if "laid_out" not in done:
                raise HTTPException(409, "finish layout before replacing evidence")
            directory = orch._job_dir(job_id)
            layout = directory / "layout.json"
            if not layout.exists():
                raise HTTPException(409, "layout is not available")
            original = layout.read_text(encoding="utf-8")
            doc = json.loads(original)
            target = next((e for e in doc["elements"] if e["id"] == element_id), None)
            if creating:
                if target is not None:
                    raise HTTPException(409, "element ID already exists")
                if not doc.get("board_timeline"):
                    raise HTTPException(409, "new evidence requires an authored board timeline")
                scene_ids = {e["scene_id"] for e in doc["elements"]}
                script_file = directory / "script.json"
                if script_file.exists():
                    scene_ids = {s["scene_id"] for s in json.loads(script_file.read_text(encoding="utf-8"))["scenes"]}
                if type(placement["scene_id"]) is not int or placement["scene_id"] not in scene_ids:
                    raise HTTPException(400, "unknown scene")
                target = {"id": element_id, "type": "evidence_image", "enter_action": "reveal", **placement}
                doc["elements"].append(target)
            elif target is None or target.get("type") != "evidence_image":
                raise HTTPException(404, "no such evidence slot")
            target.update(payload)
            try:
                LayoutDoc.model_validate(doc)
            except ValueError:
                raise HTTPException(400, "invalid evidence image or provenance")
            if creating:
                if (target["x"] + target["width"] > doc["canvas"]["width"]
                        or target["y"] + target["height"] > doc["canvas"]["height"]):
                    raise HTTPException(400, "evidence placement exceeds canvas")
                if not any(a["board_id"] == target["board_id"]
                           and a["start_ms"] <= target["appear_at_ms"] < a["end_ms"]
                           for a in doc["board_timeline"]["activations"]):
                    raise HTTPException(400, "selected board is not active at reveal time")
            revision = uuid4().hex
            backup = directory / ("layout.before-evidence-" + revision + ".json")
            backup.write_text(original, encoding="utf-8")
            pending = directory / ("layout.evidence-" + revision + ".pending.json")
            pending.write_text(json.dumps(doc, indent=2), encoding="utf-8")
            # Reset first: a crash can require rerendering the old layout, but cannot
            # leave the new layout marked as already rendered. Worker starts share lock.
            store.reset_from_stage(job_id, "aligned")
            pending.replace(layout)
            store.set_job_status(job_id, "paused")
            store.log(job_id, "evidence saved; alignment/render pending; backup " + backup.name)
        return {"saved": True, "element_id": element_id, "status": "paused",
                "revision": revision, "requires_realign": True}

    @app.get("/jobs/{job_id}/narration-events", dependencies=[Depends(auth)])
    def narration_events(job_id: int) -> dict:
        if orch is None:
            raise HTTPException(503, "orchestrator not wired")
        if not store.get_job(job_id):
            raise HTTPException(404, "no such job")
        report_file = orch._job_dir(job_id) / "narration_events.json"
        if not report_file.exists():
            return {"status": "not_available", "events": []}
        try:
            events = json.loads(report_file.read_text(encoding="utf-8"))
            if not isinstance(events, list) or any(not isinstance(e, dict) for e in events):
                raise ValueError("invalid report")
        except (OSError, ValueError):
            raise HTTPException(409, "timing report is unavailable or incomplete")
        return {"status": ("no_triggers" if not events else
                           "resolved" if all(e.get("status") == "resolved" for e in events)
                           else "needs_review"), "events": events}

    @app.get("/jobs/{job_id}/script", dependencies=[Depends(auth)])
    def job_script(job_id: int) -> dict:
        jdir = orch._job_dir(job_id) if orch is not None else None
        if jdir is None:
            raise HTTPException(503, "orchestrator not wired")
        sp = jdir / "script.json"
        if not sp.exists():
            raise HTTPException(404, "script not ready")
        return json.loads(sp.read_text(encoding="utf-8"))

    @app.get("/jobs/{job_id}/preview/{scene_id}", dependencies=[Depends(auth)])
    def scene_preview(job_id: int, scene_id: int):
        jdir = orch._job_dir(job_id) if orch is not None else None
        if jdir is None:
            raise HTTPException(503, "orchestrator not wired")
        sp = jdir / "script.json"
        if not sp.exists():
            raise HTTPException(404, "script not ready")
        script = json.loads(sp.read_text(encoding="utf-8"))
        if scene_id not in {int(scene["scene_id"]) for scene in script["scenes"]}:
            raise HTTPException(404, "scene not found")
        starts, cursor = [], 0
        for scene in script["scenes"]:
            starts.append(cursor)
            cursor += int((scene.get("est_seconds") or
                           len(scene["spoken_text"].split()) / 2.5) * 1000)
        from atme.render.animator import build_draw_windows
        from atme.render.autolayout import build_layout
        from atme.render.svg_builder import (element_stroke_info, frame_svg)
        from fastapi.responses import Response

        layout_file = jdir / "layout.json"
        actual_layout = layout_file.exists()
        if actual_layout:
            doc = json.loads(layout_file.read_text(encoding="utf-8"))
        else:
            doc = build_layout(script["scenes"], starts, title=script.get("title"))
            doc["elements"] = [element for element in doc["elements"]
                               if int(element["scene_id"]) <= scene_id]
        infos = {element["id"]: element_stroke_info(element, int(doc["seed"]))
                 for element in doc["elements"]}
        windows = build_draw_windows(doc["elements"])
        selected = [element for element in doc["elements"]
                    if int(element["scene_id"]) == scene_id] if actual_layout else doc["elements"]
        final_ms = max((int(element["appear_at_ms"]) + windows[element["id"]] + 1
                        for element in selected), default=0)
        activations = doc.get("board_timeline", {}).get("activations", [])
        if activations:
            final_ms = min(final_ms, max(a["end_ms"] for a in activations) - 1)
        from atme.render.camera import viewbox_at

        view = (viewbox_at(doc.get("camera_plan", []), doc["canvas"]["width"],
                           doc["canvas"]["height"], final_ms, 640, 360)
                if actual_layout else
                {"x": 0, "y": 0, "w": doc["canvas"]["width"],
                 "h": doc["canvas"]["height"], "out_w": 640, "out_h": 360})
        svg = frame_svg(
            doc, infos, final_ms, windows, view)
        return Response(svg, media_type="image/svg+xml",
                        headers={"Cache-Control": "no-store"})

    @app.get("/jobs/{job_id}/artifacts", dependencies=[Depends(auth)])
    def job_artifacts(job_id: int) -> dict:
        return {"artifacts": store.artifacts_for(job_id)}

    @app.get("/jobs/{job_id}/history", dependencies=[Depends(auth)])
    def job_history(job_id: int) -> dict:
        if not store.get_job(job_id):
            raise HTTPException(404, "no such job")
        with store._lock:
            events = store.conn.execute(
                "SELECT ts,level,message FROM events WHERE job_id=? ORDER BY id",
                (job_id,)).fetchall()
            usage = store.conn.execute(
                "SELECT role,model,prompt_tokens,completion_tokens,cost_usd,ok,error,wall_ms,ts "
                "FROM llm_usage WHERE job_id=? ORDER BY id", (job_id,)).fetchall()
        return {"events": [dict(row) for row in events],
                "usage": [dict(row) for row in usage]}

    @app.get("/jobs/{job_id}/events")
    async def job_events(job_id: int, token: str = "",
                         authorization: str = Header(default="")) -> dict:
        if token != _token and authorization != "Bearer %s" % _token:
            raise HTTPException(status_code=401, detail="bad token")
        q = hub.subscribe(job_id)

        async def gen():
            try:
                while True:
                    try:
                        ev = await asyncio.to_thread(q.get, True, 15)
                        yield {"event": "progress", "data": json_s(ev)}
                        if ev.get("phase") in (
                                "done", "failed", "paused", "paused_review",
                                "waiting_voice", "voice_rejected", "canceled"):
                            break
                    except queue.Empty:
                        yield {"event": "ping", "data": ""}
            finally:
                hub.unsubscribe(job_id, q)

        from fastapi.responses import StreamingResponse

        return StreamingResponse(gen(), media_type="text/event-stream")

    def json_s(obj) -> str:
        import json

        return json.dumps(obj)

    def recover_interrupted_jobs() -> None:
        with store._lock:
            rows = store.conn.execute(
                "SELECT id,status FROM jobs WHERE status IN "
                "('running','pause_requested','cancel_requested') ORDER BY id"
            ).fetchall()
        for row in rows:
            job_id, status = int(row["id"]), row["status"]
            if status == "pause_requested":
                store.set_job_status(job_id, "paused")
                store.log(job_id, "recovered requested pause after restart")
            elif status == "cancel_requested":
                store.set_job_status(job_id, "canceled")
                store.log(job_id, "completed requested cancellation after restart")
            elif orch is not None:
                store.log(job_id, "resuming interrupted job after sidecar restart")
                spawn_worker(job_id)

    app.state.hub = hub
    app.state.store = store
    return app
